/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { INamespaceStore } from "../INamespaceStore";

export class INamespaceStore__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INamespaceStore {
    return new Contract(address, _abi, signerOrProvider) as INamespaceStore;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "namespace",
        type: "uint32",
      },
    ],
    name: "NamespaceRegistered",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "namespaceId",
        type: "uint32",
      },
    ],
    name: "processContractAt",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "register",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
