/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITokenStorageProof } from "../ITokenStorageProof";

export class ITokenStorageProof__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenStorageProof {
    return new Contract(address, _abi, signerOrProvider) as ITokenStorageProof;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "ercTokenAddress",
        type: "address",
      },
    ],
    name: "getBalanceMappingPosition",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "ercTokenAddress",
        type: "address",
      },
    ],
    name: "isRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "storageProof",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "blockHeaderRLP",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "accountStateProof",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "balanceMappingPosition",
        type: "uint256",
      },
    ],
    name: "registerToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
