/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface INamespaceStoreInterface extends ethers.utils.Interface {
  functions: {
    "processContractAt(uint32)": FunctionFragment;
    "register()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "processContractAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "processContractAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;

  events: {
    "NamespaceRegistered(uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NamespaceRegistered"): EventFragment;
}

export class INamespaceStore extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: INamespaceStoreInterface;

  functions: {
    processContractAt(
      namespaceId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "processContractAt(uint32)"(
      namespaceId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    register(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "register()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  processContractAt(
    namespaceId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "processContractAt(uint32)"(
    namespaceId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  register(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "register()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    processContractAt(
      namespaceId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "processContractAt(uint32)"(
      namespaceId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    register(overrides?: CallOverrides): Promise<number>;

    "register()"(overrides?: CallOverrides): Promise<number>;
  };

  filters: {
    NamespaceRegistered(
      namespace: null
    ): TypedEventFilter<[number], { namespace: number }>;
  };

  estimateGas: {
    processContractAt(
      namespaceId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "processContractAt(uint32)"(
      namespaceId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    register(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "register()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    processContractAt(
      namespaceId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "processContractAt(uint32)"(
      namespaceId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "register()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
