/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IProcessStoreInterface extends ethers.utils.Interface {
  functions: {
    "get(bytes32)": FunctionFragment;
    "getCreationInstance(bytes32)": FunctionFragment;
    "getEntityProcessCount(address)": FunctionFragment;
    "getNextProcessId(address)": FunctionFragment;
    "getParamsSignature(bytes32)": FunctionFragment;
    "getProcessId(address,uint256,uint32,uint32)": FunctionFragment;
    "incrementQuestionIndex(bytes32)": FunctionFragment;
    "newProcess(uint8[3],address,string[3],uint32[2],uint8[4],uint16[2],uint256,bytes32)": FunctionFragment;
    "setCensus(bytes32,string,string)": FunctionFragment;
    "setProcessPrice(uint256)": FunctionFragment;
    "setStatus(bytes32,uint8)": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "get", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getCreationInstance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntityProcessCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextProcessId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getParamsSignature",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProcessId",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementQuestionIndex",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "newProcess",
    values: [
      [BigNumberish, BigNumberish, BigNumberish],
      string,
      [string, string, string],
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish],
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setCensus",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreationInstance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntityProcessCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextProcessId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParamsSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProcessId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementQuestionIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newProcess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCensus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProcessPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "CensusUpdated(bytes32,uint32)": EventFragment;
    "NewProcess(bytes32,uint32)": EventFragment;
    "ProcessPriceUpdated(uint256)": EventFragment;
    "QuestionIndexUpdated(bytes32,uint32,uint8)": EventFragment;
    "StatusUpdated(bytes32,uint32,uint8)": EventFragment;
    "Withdraw(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CensusUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProcess"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProcessPriceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuestionIndexUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StatusUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export class IProcessStore extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IProcessStoreInterface;

  functions: {
    get(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, number, number],
        string,
        [string, string, string],
        [number, number],
        number,
        [number, number, number, number, number],
        [number, number],
        BigNumber
      ] & {
        mode_envelopeType_censusOrigin: [number, number, number];
        entityAddress: string;
        metadata_censusRoot_censusUri: [string, string, string];
        startBlock_blockCount: [number, number];
        status: number;
        questionIndex_questionCount_maxCount_maxValue_maxVoteOverwrites: [
          number,
          number,
          number,
          number,
          number
        ];
        maxTotalCost_costExponent: [number, number];
        evmBlockHeight: BigNumber;
      }
    >;

    "get(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, number, number],
        string,
        [string, string, string],
        [number, number],
        number,
        [number, number, number, number, number],
        [number, number],
        BigNumber
      ] & {
        mode_envelopeType_censusOrigin: [number, number, number];
        entityAddress: string;
        metadata_censusRoot_censusUri: [string, string, string];
        startBlock_blockCount: [number, number];
        status: number;
        questionIndex_questionCount_maxCount_maxValue_maxVoteOverwrites: [
          number,
          number,
          number,
          number,
          number
        ];
        maxTotalCost_costExponent: [number, number];
        evmBlockHeight: BigNumber;
      }
    >;

    getCreationInstance(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getCreationInstance(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getEntityProcessCount(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getEntityProcessCount(address)"(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getNextProcessId(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getNextProcessId(address)"(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getParamsSignature(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getParamsSignature(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getProcessId(
      entityAddress: string,
      processCountIndex: BigNumberish,
      namespaceId: BigNumberish,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getProcessId(address,uint256,uint32,uint32)"(
      entityAddress: string,
      processCountIndex: BigNumberish,
      namespaceId: BigNumberish,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    incrementQuestionIndex(
      processId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "incrementQuestionIndex(bytes32)"(
      processId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newProcess(
      mode_envelopeType_censusOrigin: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      tokenContractAddress: string,
      metadata_censusRoot_censusUri: [string, string, string],
      startBlock_blockCount: [BigNumberish, BigNumberish],
      questionCount_maxCount_maxValue_maxVoteOverwrites: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      maxTotalCost_costExponent: [BigNumberish, BigNumberish],
      evmBlockHeight: BigNumberish,
      paramsSignature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "newProcess(uint8[3],address,string[3],uint32[2],uint8[4],uint16[2],uint256,bytes32)"(
      mode_envelopeType_censusOrigin: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      tokenContractAddress: string,
      metadata_censusRoot_censusUri: [string, string, string],
      startBlock_blockCount: [BigNumberish, BigNumberish],
      questionCount_maxCount_maxValue_maxVoteOverwrites: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      maxTotalCost_costExponent: [BigNumberish, BigNumberish],
      evmBlockHeight: BigNumberish,
      paramsSignature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCensus(
      processId: BytesLike,
      censusRoot: string,
      censusUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setCensus(bytes32,string,string)"(
      processId: BytesLike,
      censusRoot: string,
      censusUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProcessPrice(
      processPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setProcessPrice(uint256)"(
      processPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setStatus(
      processId: BytesLike,
      newStatus: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setStatus(bytes32,uint8)"(
      processId: BytesLike,
      newStatus: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdraw(address,uint256)"(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  get(
    processId: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [
      [number, number, number],
      string,
      [string, string, string],
      [number, number],
      number,
      [number, number, number, number, number],
      [number, number],
      BigNumber
    ] & {
      mode_envelopeType_censusOrigin: [number, number, number];
      entityAddress: string;
      metadata_censusRoot_censusUri: [string, string, string];
      startBlock_blockCount: [number, number];
      status: number;
      questionIndex_questionCount_maxCount_maxValue_maxVoteOverwrites: [
        number,
        number,
        number,
        number,
        number
      ];
      maxTotalCost_costExponent: [number, number];
      evmBlockHeight: BigNumber;
    }
  >;

  "get(bytes32)"(
    processId: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [
      [number, number, number],
      string,
      [string, string, string],
      [number, number],
      number,
      [number, number, number, number, number],
      [number, number],
      BigNumber
    ] & {
      mode_envelopeType_censusOrigin: [number, number, number];
      entityAddress: string;
      metadata_censusRoot_censusUri: [string, string, string];
      startBlock_blockCount: [number, number];
      status: number;
      questionIndex_questionCount_maxCount_maxValue_maxVoteOverwrites: [
        number,
        number,
        number,
        number,
        number
      ];
      maxTotalCost_costExponent: [number, number];
      evmBlockHeight: BigNumber;
    }
  >;

  getCreationInstance(
    processId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getCreationInstance(bytes32)"(
    processId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getEntityProcessCount(
    entityAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getEntityProcessCount(address)"(
    entityAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNextProcessId(
    entityAddress: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getNextProcessId(address)"(
    entityAddress: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getParamsSignature(
    processId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getParamsSignature(bytes32)"(
    processId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getProcessId(
    entityAddress: string,
    processCountIndex: BigNumberish,
    namespaceId: BigNumberish,
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getProcessId(address,uint256,uint32,uint32)"(
    entityAddress: string,
    processCountIndex: BigNumberish,
    namespaceId: BigNumberish,
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  incrementQuestionIndex(
    processId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "incrementQuestionIndex(bytes32)"(
    processId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newProcess(
    mode_envelopeType_censusOrigin: [BigNumberish, BigNumberish, BigNumberish],
    tokenContractAddress: string,
    metadata_censusRoot_censusUri: [string, string, string],
    startBlock_blockCount: [BigNumberish, BigNumberish],
    questionCount_maxCount_maxValue_maxVoteOverwrites: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    maxTotalCost_costExponent: [BigNumberish, BigNumberish],
    evmBlockHeight: BigNumberish,
    paramsSignature: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "newProcess(uint8[3],address,string[3],uint32[2],uint8[4],uint16[2],uint256,bytes32)"(
    mode_envelopeType_censusOrigin: [BigNumberish, BigNumberish, BigNumberish],
    tokenContractAddress: string,
    metadata_censusRoot_censusUri: [string, string, string],
    startBlock_blockCount: [BigNumberish, BigNumberish],
    questionCount_maxCount_maxValue_maxVoteOverwrites: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    maxTotalCost_costExponent: [BigNumberish, BigNumberish],
    evmBlockHeight: BigNumberish,
    paramsSignature: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCensus(
    processId: BytesLike,
    censusRoot: string,
    censusUri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setCensus(bytes32,string,string)"(
    processId: BytesLike,
    censusRoot: string,
    censusUri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProcessPrice(
    processPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setProcessPrice(uint256)"(
    processPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setStatus(
    processId: BytesLike,
    newStatus: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setStatus(bytes32,uint8)"(
    processId: BytesLike,
    newStatus: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdraw(address,uint256)"(
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    get(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, number, number],
        string,
        [string, string, string],
        [number, number],
        number,
        [number, number, number, number, number],
        [number, number],
        BigNumber
      ] & {
        mode_envelopeType_censusOrigin: [number, number, number];
        entityAddress: string;
        metadata_censusRoot_censusUri: [string, string, string];
        startBlock_blockCount: [number, number];
        status: number;
        questionIndex_questionCount_maxCount_maxValue_maxVoteOverwrites: [
          number,
          number,
          number,
          number,
          number
        ];
        maxTotalCost_costExponent: [number, number];
        evmBlockHeight: BigNumber;
      }
    >;

    "get(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, number, number],
        string,
        [string, string, string],
        [number, number],
        number,
        [number, number, number, number, number],
        [number, number],
        BigNumber
      ] & {
        mode_envelopeType_censusOrigin: [number, number, number];
        entityAddress: string;
        metadata_censusRoot_censusUri: [string, string, string];
        startBlock_blockCount: [number, number];
        status: number;
        questionIndex_questionCount_maxCount_maxValue_maxVoteOverwrites: [
          number,
          number,
          number,
          number,
          number
        ];
        maxTotalCost_costExponent: [number, number];
        evmBlockHeight: BigNumber;
      }
    >;

    getCreationInstance(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getCreationInstance(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getEntityProcessCount(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getEntityProcessCount(address)"(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNextProcessId(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getNextProcessId(address)"(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getParamsSignature(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getParamsSignature(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getProcessId(
      entityAddress: string,
      processCountIndex: BigNumberish,
      namespaceId: BigNumberish,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getProcessId(address,uint256,uint32,uint32)"(
      entityAddress: string,
      processCountIndex: BigNumberish,
      namespaceId: BigNumberish,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    incrementQuestionIndex(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "incrementQuestionIndex(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    newProcess(
      mode_envelopeType_censusOrigin: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      tokenContractAddress: string,
      metadata_censusRoot_censusUri: [string, string, string],
      startBlock_blockCount: [BigNumberish, BigNumberish],
      questionCount_maxCount_maxValue_maxVoteOverwrites: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      maxTotalCost_costExponent: [BigNumberish, BigNumberish],
      evmBlockHeight: BigNumberish,
      paramsSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "newProcess(uint8[3],address,string[3],uint32[2],uint8[4],uint16[2],uint256,bytes32)"(
      mode_envelopeType_censusOrigin: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      tokenContractAddress: string,
      metadata_censusRoot_censusUri: [string, string, string],
      startBlock_blockCount: [BigNumberish, BigNumberish],
      questionCount_maxCount_maxValue_maxVoteOverwrites: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      maxTotalCost_costExponent: [BigNumberish, BigNumberish],
      evmBlockHeight: BigNumberish,
      paramsSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setCensus(
      processId: BytesLike,
      censusRoot: string,
      censusUri: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setCensus(bytes32,string,string)"(
      processId: BytesLike,
      censusRoot: string,
      censusUri: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setProcessPrice(
      processPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setProcessPrice(uint256)"(
      processPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setStatus(
      processId: BytesLike,
      newStatus: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setStatus(bytes32,uint8)"(
      processId: BytesLike,
      newStatus: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdraw(address,uint256)"(
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    CensusUpdated(
      processId: null,
      namespace: null
    ): TypedEventFilter<
      [string, number],
      { processId: string; namespace: number }
    >;

    NewProcess(
      processId: null,
      namespace: null
    ): TypedEventFilter<
      [string, number],
      { processId: string; namespace: number }
    >;

    ProcessPriceUpdated(
      processPrice: null
    ): TypedEventFilter<[BigNumber], { processPrice: BigNumber }>;

    QuestionIndexUpdated(
      processId: null,
      namespace: null,
      newIndex: null
    ): TypedEventFilter<
      [string, number, number],
      { processId: string; namespace: number; newIndex: number }
    >;

    StatusUpdated(
      processId: null,
      namespace: null,
      status: null
    ): TypedEventFilter<
      [string, number, number],
      { processId: string; namespace: number; status: number }
    >;

    Withdraw(
      to: null,
      amount: null
    ): TypedEventFilter<[string, BigNumber], { to: string; amount: BigNumber }>;
  };

  estimateGas: {
    get(processId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "get(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreationInstance(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCreationInstance(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntityProcessCount(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getEntityProcessCount(address)"(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNextProcessId(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNextProcessId(address)"(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getParamsSignature(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getParamsSignature(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProcessId(
      entityAddress: string,
      processCountIndex: BigNumberish,
      namespaceId: BigNumberish,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getProcessId(address,uint256,uint32,uint32)"(
      entityAddress: string,
      processCountIndex: BigNumberish,
      namespaceId: BigNumberish,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incrementQuestionIndex(
      processId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "incrementQuestionIndex(bytes32)"(
      processId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newProcess(
      mode_envelopeType_censusOrigin: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      tokenContractAddress: string,
      metadata_censusRoot_censusUri: [string, string, string],
      startBlock_blockCount: [BigNumberish, BigNumberish],
      questionCount_maxCount_maxValue_maxVoteOverwrites: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      maxTotalCost_costExponent: [BigNumberish, BigNumberish],
      evmBlockHeight: BigNumberish,
      paramsSignature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "newProcess(uint8[3],address,string[3],uint32[2],uint8[4],uint16[2],uint256,bytes32)"(
      mode_envelopeType_censusOrigin: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      tokenContractAddress: string,
      metadata_censusRoot_censusUri: [string, string, string],
      startBlock_blockCount: [BigNumberish, BigNumberish],
      questionCount_maxCount_maxValue_maxVoteOverwrites: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      maxTotalCost_costExponent: [BigNumberish, BigNumberish],
      evmBlockHeight: BigNumberish,
      paramsSignature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCensus(
      processId: BytesLike,
      censusRoot: string,
      censusUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setCensus(bytes32,string,string)"(
      processId: BytesLike,
      censusRoot: string,
      censusUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProcessPrice(
      processPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setProcessPrice(uint256)"(
      processPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setStatus(
      processId: BytesLike,
      newStatus: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setStatus(bytes32,uint8)"(
      processId: BytesLike,
      newStatus: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdraw(address,uint256)"(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    get(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "get(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreationInstance(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCreationInstance(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntityProcessCount(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEntityProcessCount(address)"(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNextProcessId(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNextProcessId(address)"(
      entityAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getParamsSignature(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getParamsSignature(bytes32)"(
      processId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProcessId(
      entityAddress: string,
      processCountIndex: BigNumberish,
      namespaceId: BigNumberish,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getProcessId(address,uint256,uint32,uint32)"(
      entityAddress: string,
      processCountIndex: BigNumberish,
      namespaceId: BigNumberish,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    incrementQuestionIndex(
      processId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "incrementQuestionIndex(bytes32)"(
      processId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newProcess(
      mode_envelopeType_censusOrigin: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      tokenContractAddress: string,
      metadata_censusRoot_censusUri: [string, string, string],
      startBlock_blockCount: [BigNumberish, BigNumberish],
      questionCount_maxCount_maxValue_maxVoteOverwrites: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      maxTotalCost_costExponent: [BigNumberish, BigNumberish],
      evmBlockHeight: BigNumberish,
      paramsSignature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "newProcess(uint8[3],address,string[3],uint32[2],uint8[4],uint16[2],uint256,bytes32)"(
      mode_envelopeType_censusOrigin: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      tokenContractAddress: string,
      metadata_censusRoot_censusUri: [string, string, string],
      startBlock_blockCount: [BigNumberish, BigNumberish],
      questionCount_maxCount_maxValue_maxVoteOverwrites: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      maxTotalCost_costExponent: [BigNumberish, BigNumberish],
      evmBlockHeight: BigNumberish,
      paramsSignature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCensus(
      processId: BytesLike,
      censusRoot: string,
      censusUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setCensus(bytes32,string,string)"(
      processId: BytesLike,
      censusRoot: string,
      censusUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProcessPrice(
      processPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setProcessPrice(uint256)"(
      processPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setStatus(
      processId: BytesLike,
      newStatus: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setStatus(bytes32,uint8)"(
      processId: BytesLike,
      newStatus: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdraw(address,uint256)"(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
