/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ITokenStorageProofInterface extends ethers.utils.Interface {
  functions: {
    "getBalanceMappingPosition(address)": FunctionFragment;
    "isRegistered(address)": FunctionFragment;
    "registerToken(address,uint256,bytes,bytes,bytes,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBalanceMappingPosition",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerToken",
    values: [
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBalanceMappingPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class ITokenStorageProof extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ITokenStorageProofInterface;

  functions: {
    getBalanceMappingPosition(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getBalanceMappingPosition(address)"(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isRegistered(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isRegistered(address)"(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    registerToken(
      token: string,
      blockNumber: BigNumberish,
      storageProof: BytesLike,
      blockHeaderRLP: BytesLike,
      accountStateProof: BytesLike,
      balanceMappingPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "registerToken(address,uint256,bytes,bytes,bytes,uint256)"(
      token: string,
      blockNumber: BigNumberish,
      storageProof: BytesLike,
      blockHeaderRLP: BytesLike,
      accountStateProof: BytesLike,
      balanceMappingPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getBalanceMappingPosition(
    ercTokenAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getBalanceMappingPosition(address)"(
    ercTokenAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isRegistered(
    ercTokenAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isRegistered(address)"(
    ercTokenAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  registerToken(
    token: string,
    blockNumber: BigNumberish,
    storageProof: BytesLike,
    blockHeaderRLP: BytesLike,
    accountStateProof: BytesLike,
    balanceMappingPosition: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "registerToken(address,uint256,bytes,bytes,bytes,uint256)"(
    token: string,
    blockNumber: BigNumberish,
    storageProof: BytesLike,
    blockHeaderRLP: BytesLike,
    accountStateProof: BytesLike,
    balanceMappingPosition: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getBalanceMappingPosition(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBalanceMappingPosition(address)"(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRegistered(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isRegistered(address)"(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    registerToken(
      token: string,
      blockNumber: BigNumberish,
      storageProof: BytesLike,
      blockHeaderRLP: BytesLike,
      accountStateProof: BytesLike,
      balanceMappingPosition: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerToken(address,uint256,bytes,bytes,bytes,uint256)"(
      token: string,
      blockNumber: BigNumberish,
      storageProof: BytesLike,
      blockHeaderRLP: BytesLike,
      accountStateProof: BytesLike,
      balanceMappingPosition: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getBalanceMappingPosition(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getBalanceMappingPosition(address)"(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRegistered(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isRegistered(address)"(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerToken(
      token: string,
      blockNumber: BigNumberish,
      storageProof: BytesLike,
      blockHeaderRLP: BytesLike,
      accountStateProof: BytesLike,
      balanceMappingPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "registerToken(address,uint256,bytes,bytes,bytes,uint256)"(
      token: string,
      blockNumber: BigNumberish,
      storageProof: BytesLike,
      blockHeaderRLP: BytesLike,
      accountStateProof: BytesLike,
      balanceMappingPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBalanceMappingPosition(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBalanceMappingPosition(address)"(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRegistered(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isRegistered(address)"(
      ercTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerToken(
      token: string,
      blockNumber: BigNumberish,
      storageProof: BytesLike,
      blockHeaderRLP: BytesLike,
      accountStateProof: BytesLike,
      balanceMappingPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "registerToken(address,uint256,bytes,bytes,bytes,uint256)"(
      token: string,
      blockNumber: BigNumberish,
      storageProof: BytesLike,
      blockHeaderRLP: BytesLike,
      accountStateProof: BytesLike,
      balanceMappingPosition: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
